In [3]:
import pandas as pd

In [3]:
info = {
    'name': ['Suraj', 'Kiran', 'Panda'],
    'CGPA': [9.5, 9.6, 9.3]
}

#data frame (2-D labled array)
df = pd.DataFrame(info)
print(df)

    name  CGPA
0  Suraj   9.5
1  Kiran   9.6
2  Panda   9.3

In [4]:
df

    name  CGPA
0  Suraj   9.5
1  Kiran   9.6
2  Panda   9.3

In [8]:
#Series (labled array)
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[0])
print(s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
2

In [11]:
s = pd.Series([23, 24, 25, 26], index = ['Adam', 'Eve', 'Bob', 'Charlie'])
print(s)

print(s['Adam'])

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23

In [5]:
#vectorization
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1 + s2)
cs = s1.drop(0)
print(cs)
print(s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
#dataframe
info = {
    'name': ['Suraj', 'Kiran', 'Panda'],
    'Age': [23, 24, 25],
    'CGPA': [9.5, 9.6, 9.3]
}

#data frame (2-D labled array)
df = pd.DataFrame(info)
print(df)

    name  Age  CGPA
0  Suraj   23   9.5
1  Kiran   24   9.6
2  Panda   25   9.3

In [8]:
df

    name  Age  CGPA
0  Suraj   23   9.5
1  Kiran   24   9.6
2  Panda   25   9.3

In [10]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'Age', 'CGPA'], dtype='object')

In [12]:
#manual
df = pd.DataFrame([['Adam', 23], ['Bob', 24], ['Eve', 23]], columns = ['Name', 'Age'])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   23

In [14]:
import numpy as np

#from numpy array
np_arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_arr, columns = ['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [17]:
#csv data
df = pd.read_csv('employee_data.csv')
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [32]:
#methods
df.head() #starting 5 rows
df.tail() #last 5 rows
df.sample() #random row
df.info() #information
df.shape #(row, column)
df.describe() #stats of numerical cols
df.columns #columns
df.nunique() #number of unique values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [35]:
#AQI dataset from KAGGLE
data = pd.read_csv('globalAirQuality.csv')
data.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [53]:
#Selecting the data

#column
data['city']
data[['city', 'aqi']]

#Row
data.loc[0] # 0th level
data.loc[0:2] #0-2th level (start, end) end inclusive

data.iloc[0] # 0th index
data.iloc[0:2] #0-2th index (start, end) end exclusive

#Individual cells
data.loc[0:1, ['city','aqi']]
data.iloc[0:2, 2] #it takes only numeric value
data.loc[0:2, ['country', 'city', 'latitude', 'longitude']]
data.iloc[0:2, 1:5]

data.at[0, 'city']

#copy and view
cities = data['city'] #view (any change can be shown in real data)
cities = data['city'].copy() #copy (can't change the original data)

'New York'

In [66]:
#Filtering data
data[data['aqi'] > 100]
data[(data['aqi'] > 100) & (data['temperature'] > 30)]
data[(data['aqi'] > 100) & (data['temperature'] < 30)]

aqi_data = data[(data['aqi'] > 100) & (data['temperature'] > 30)] [['city','aqi']]
aqi_data.iloc[0] #index values
aqi_data.loc[6] #level values

city    New York
aqi          155
Name: 6, dtype: object

In [71]:
#Query methods (returns copy)
data.query('aqi > 100 & temperature > 30')[['city','aqi']]

#variable
aqi_val = 100
data.query('aqi > @aqi_val & temperature > 30')[['city','aqi']]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [4]:
#Cleaning data
#Missing values
df = pd.read_csv('raw_data.csv')

df.isnull() #true for missing, false for others
df.isnull().sum() #count col wise number of missing values
df.dropna() #delete all rows with empty col
df.dropna(axis = 1) #delete all cols with empty val
df.fillna(0) #fill missing val with any val
cleaned_data = df.copy()
cleaned_data['age'] = cleaned_data['age'].fillna(cleaned_data['age'].mean()) #with mean for age
cleaned_data
df.ffill() #Forward fill
df.bfill() #Backward fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [87]:
#Handle duplicates
df.duplicated()
df['country'].duplicated()
df[['country', 'gender']].duplicated()
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
#Data types
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2['age'] = df2['age'].astype('int64').copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [73]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [12]:
data = pd.read_csv('globalAirQuality.csv')
data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [14]:
date = pd.Series([pd.to_datetime('2026-12-31')])
type(date.dtypes)

numpy.dtypes.DateTime64DType

In [16]:
#Strings in pandas
df['gender'].str.upper()
df['name'].str.split(' ')

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object